import { Check, CheckCheck, Clipboard, CircleAlert, CircleCheck, ExternalLink, MessageCircle, RefreshCw, Send, ShieldCheck, Wifi } from 'lucide-react';
import { useState } from 'react';
import { getGetBotStatusQueryKey, getHealthCheckQueryKey, getListFaqsQueryKey, useGetBotStatus, useHealthCheck, useListFaqs } from '@workspace/api-client-react';
import { AppShell } from '@/components/shell';
import { Button, ErrorState, PageHeader, inputClass } from '@/components/common';
import { useToast } from '@/hooks/use-toast';

type Message = { from: 'bot' | 'client'; text: string };
const initialMessages: Message[] = [{ from: 'bot', text: 'Hola, soy el asistente de estética. ¿En qué puedo ayudarte hoy?' }, { from: 'client', text: 'Hola, quisiera saber qué incluye una limpieza facial.' }, { from: 'bot', text: 'Con gusto. Puedo contarte sobre el tratamiento, su duración y ayudarte a encontrar un horario.' }];

export default function Bot() {
  const status = useGetBotStatus({ query: { queryKey: getGetBotStatusQueryKey() } }); const health = useHealthCheck({ query: { queryKey: getHealthCheckQueryKey() } }); const faqs = useListFaqs(undefined, { query: { queryKey: getListFaqsQueryKey(undefined) } });
  const [messages, setMessages] = useState<Message[]>(initialMessages); const [draft, setDraft] = useState(''); const { toast } = useToast();
  const bot = status.data; const send = () => { const value = draft.trim(); if (!value) return; setMessages((current) => [...current, { from: 'client', text: value }, { from: 'bot', text: 'Gracias por escribirnos. Esta es una simulación para revisar el tono de tus respuestas.' }]); setDraft(''); };
  const copyWebhook = () => { void navigator.clipboard?.writeText('/api/webhooks/whatsapp'); toast({ title: 'Ruta copiada', description: 'Ya puedes compartirla con tu proveedor de WhatsApp.' }); };
  return <AppShell><PageHeader eyebrow="Puente con tus conversaciones" title="Conexión WhatsApp" description="Revisa que todo esté listo antes de dejar que el bot acompañe a tus clientes." action={<Button variant="secondary" onClick={() => void status.refetch()} data-testid="button-refresh-bot"><RefreshCw size={15} />Actualizar estado</Button>} />
    <div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]">
      <section className="surface overflow-hidden rounded-2xl"><div className="border-b border-border/70 px-5 py-5"><div className="flex items-center gap-3"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${bot?.connected ? 'bg-primary/10 text-primary' : 'bg-accent/30 text-[hsl(32_44%_30%)]'}`}><Wifi size={19} /></span><div><h2 className="text-[15px] font-semibold">Estado de conexión</h2><p className="mt-1 text-xs text-muted-foreground">Última lectura del canal de atención</p></div><span className={`ml-auto rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.1em] ${bot?.connected ? 'bg-primary/10 text-primary' : 'bg-accent/30 text-[hsl(32_44%_30%)]'}`}>{bot?.connected ? 'En línea' : 'Sin conectar'}</span></div></div>
        {status.isLoading ? <div className="space-y-4 p-5"><div className="h-10 animate-pulse rounded-xl bg-muted" /><div className="h-20 animate-pulse rounded-xl bg-muted" /><div className="h-10 animate-pulse rounded-xl bg-muted" /></div> : status.isError ? <div className="p-5"><ErrorState onRetry={() => void status.refetch()} /></div> : <div className="space-y-3 p-5"><div className="flex items-center justify-between rounded-xl bg-muted/50 p-4"><span className="text-xs text-muted-foreground">Proveedor</span><span className="text-sm font-semibold">{bot?.provider || 'No configurado'}</span></div><div className="flex items-center justify-between rounded-xl bg-muted/50 p-4"><span className="text-xs text-muted-foreground">Identificador</span><span className="text-sm font-semibold">{bot?.label || 'Pendiente de configuración'}</span></div><div className="flex items-center justify-between rounded-xl bg-muted/50 p-4"><span className="flex items-center gap-2 text-xs text-muted-foreground"><span className={`h-2 w-2 rounded-full ${bot?.webhookReady ? 'bg-primary' : 'bg-accent'}`} />Webhook</span><span className={`text-sm font-semibold ${bot?.webhookReady ? 'text-primary' : 'text-[hsl(32_44%_30%)]'}`}>{bot?.webhookReady ? 'Listo para recibir' : 'Requiere atención'}</span></div></div>}
      </section>
      <section className="rounded-2xl bg-secondary/70 p-5"><div className="flex items-center gap-2 text-primary"><ShieldCheck size={17} /><p className="text-[11px] font-bold uppercase tracking-[.15em]">Preparación técnica</p></div><h2 className="serif mt-4 text-2xl">Todo en orden, paso a paso.</h2><div className="mt-5 space-y-4">{[{ label: 'Servicio disponible', detail: 'API operativa', ok: health.data?.status === 'ok' || !health.isError }, { label: 'Respuestas cargadas', detail: `${faqs.data?.length ?? 0} respuestas activas`, ok: true }, { label: 'Webhook preparado', detail: bot?.webhookReady ? 'Conectado' : 'Pendiente', ok: Boolean(bot?.webhookReady) }].map((item) => <div key={item.label} className="flex items-center gap-3"><span className={`flex h-7 w-7 items-center justify-center rounded-full ${item.ok ? 'bg-primary text-primary-foreground' : 'bg-accent text-[hsl(32_44%_30%)]'}`}>{item.ok ? <Check size={14} /> : <CircleAlert size={14} />}</span><div className="flex-1"><p className="text-xs font-semibold">{item.label}</p><p className="text-[11px] text-muted-foreground">{item.detail}</p></div></div>)}</div></section>
    </div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.15fr_.85fr]">
      <section className="surface rounded-2xl p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-[15px] font-semibold">Simulador de conversación</h2><p className="mt-1 text-xs text-muted-foreground">Prueba cómo responde el bot con tus preguntas frecuentes.</p></div><MessageCircle size={19} className="text-primary" /></div><div className="min-h-[330px] space-y-3 rounded-2xl bg-[hsl(36_33%_94%)] p-4 dark:bg-muted/40">{messages.map((message, index) => <div key={`${message.from}-${index}`} className={`flex ${message.from === 'client' ? 'justify-end' : 'justify-start'}`} data-testid={`message-simulator-${index}`}><div className={`max-w-[82%] rounded-2xl px-3.5 py-2.5 text-sm leading-relaxed ${message.from === 'client' ? 'rounded-br-md bg-primary text-primary-foreground' : 'rounded-bl-md bg-card text-foreground shadow-sm'}`}>{message.text}<div className={`mt-1 flex items-center justify-end gap-1 text-[10px] ${message.from === 'client' ? 'text-primary-foreground/65' : 'text-muted-foreground'}`}><span>10:24</span>{message.from === 'client' && <CheckCheck size={12} />}</div></div></div>)}</div><div className="mt-3 flex gap-2"><input value={draft} onChange={(e) => setDraft(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') send(); }} className={`${inputClass} flex-1`} placeholder="Escribe una pregunta para probar..." aria-label="Mensaje de simulación" data-testid="input-simulator-message" /><Button onClick={send} className="h-10 w-10 px-0" aria-label="Enviar mensaje" data-testid="button-send-simulator"><Send size={15} /></Button></div></section>
      <section className="surface rounded-2xl p-5"><div className="mb-5 flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-accent/35 text-[hsl(32_44%_30%)]"><Clipboard size={17} /></span><div><h2 className="text-[15px] font-semibold">Detalles del webhook</h2><p className="mt-1 text-xs text-muted-foreground">Comparte estos datos con tu proveedor.</p></div></div><div className="space-y-4"><div><p className="mb-2 text-[10px] font-bold uppercase tracking-[.12em] text-muted-foreground">Ruta de recepción</p><div className="flex items-center gap-2 rounded-xl border border-input bg-muted/40 p-3"><code className="min-w-0 flex-1 truncate text-xs text-primary">/api/webhooks/whatsapp</code><button onClick={copyWebhook} className="rounded-lg p-1.5 text-muted-foreground hover:bg-muted hover:text-foreground" aria-label="Copiar ruta" data-testid="button-copy-webhook"><Clipboard size={14} /></button></div></div><div className="rounded-xl border border-primary/15 bg-primary/5 p-4"><div className="flex items-center gap-2"><CircleCheck size={16} className="text-primary" /><p className="text-xs font-semibold">Lista de comprobación</p></div><ul className="mt-3 space-y-2 text-xs text-muted-foreground"><li className="flex items-center gap-2"><Check size={13} className="text-primary" />URL registrada en el proveedor</li><li className="flex items-center gap-2"><Check size={13} className="text-primary" />Eventos de mensajes habilitados</li><li className="flex items-center gap-2"><Check size={13} className="text-primary" />Preguntas y tratamientos actualizados</li></ul></div><a href="https://developers.facebook.com/docs/whatsapp/cloud-api/webhooks" target="_blank" rel="noreferrer" className="flex items-center gap-2 text-xs font-semibold text-primary hover:underline" data-testid="link-webhook-docs">Ver documentación de referencia <ExternalLink size={13} /></a></div></section>
    </div>
  </AppShell>;
}