import { ArrowUpRight, CircleHelp, Pencil, Plus, Search, Trash2 } from 'lucide-react';
import { useMemo, useState } from 'react';
import { getListFaqsQueryKey, getListServicesQueryKey, useCreateFaq, useDeleteFaq, useListFaqs, useListServices, useUpdateFaq, type Faq, type Service } from '@workspace/api-client-react';
import { useQueryClient } from '@tanstack/react-query';
import { AppShell } from '@/components/shell';
import { Button, EmptyState, ErrorState, Field, LoadingRows, Modal, PageHeader, SavingButton, SelectChevron, StatusPill, inputClass, textareaClass } from '@/components/common';
import { useToast } from '@/hooks/use-toast';

type FaqForm = { serviceId: string; question: string; answer: string; priority: string; active: boolean };
const blank: FaqForm = { serviceId: '', question: '', answer: '', priority: '0', active: true };

function FaqEditor({ faq, services, onClose }: { faq?: Faq; services: Service[]; onClose: () => void }) {
  const [form, setForm] = useState<FaqForm>(faq ? { serviceId: faq.serviceId ? String(faq.serviceId) : '', question: faq.question, answer: faq.answer, priority: String(faq.priority), active: faq.active } : blank);
  const create = useCreateFaq(); const update = useUpdateFaq(); const client = useQueryClient(); const { toast } = useToast(); const pending = create.isPending || update.isPending;
  const change = (key: keyof FaqForm, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
  const submit = (event: React.FormEvent) => { event.preventDefault(); const data = { serviceId: form.serviceId ? Number(form.serviceId) : null, question: form.question.trim(), answer: form.answer.trim(), priority: Number(form.priority) || 0, active: form.active }; const options = { onSuccess: () => { void client.invalidateQueries({ queryKey: getListFaqsQueryKey() }); toast({ title: faq ? 'Respuesta actualizada' : 'Pregunta agregada', description: 'El bot ya tiene esta información disponible.' }); onClose(); }, onError: () => toast({ title: 'No se pudo guardar la respuesta', description: 'Revisa los campos e intenta de nuevo.', variant: 'destructive' as const }) }; if (faq) update.mutate({ id: faq.id, data }, options); else create.mutate({ data }, options); };
  return <Modal title={faq ? 'Editar pregunta' : 'Nueva pregunta'} description="Una respuesta precisa evita conversaciones innecesarias." onClose={onClose} wide><form onSubmit={submit} className="space-y-5"><Field label="Tratamiento relacionado" hint="Opcional: úsalo para agrupar respuestas por servicio."><div className="relative"><select value={form.serviceId} onChange={(e) => change('serviceId', e.target.value)} className={`${inputClass} appearance-none`} data-testid="select-faq-service"><option value="">General de la clínica</option>{services.map((service) => <option key={service.id} value={service.id}>{service.name}</option>)}</select><SelectChevron /></div></Field><Field label="Pregunta"><input required value={form.question} onChange={(e) => change('question', e.target.value)} className={inputClass} placeholder="¿Cuánto dura una limpieza facial?" data-testid="input-faq-question" /></Field><Field label="Respuesta"><textarea required value={form.answer} onChange={(e) => change('answer', e.target.value)} className={`${textareaClass} min-h-[130px]`} placeholder="Responde como lo haría tu equipo de recepción..." data-testid="input-faq-answer" /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Prioridad" hint="0 es la prioridad más baja."><input min="0" type="number" value={form.priority} onChange={(e) => change('priority', e.target.value)} className={inputClass} data-testid="input-faq-priority" /></Field><label className="flex items-center gap-3 self-end rounded-xl bg-muted/60 p-3 text-sm"><input type="checkbox" checked={form.active} onChange={(e) => change('active', e.target.checked)} className="h-4 w-4 accent-primary" data-testid="input-faq-active" /><span><span className="block font-semibold">Respuesta activa</span><span className="block text-xs text-muted-foreground">Visible para el bot</span></span></label></div><div className="flex justify-end gap-2 pt-2"><Button type="button" variant="ghost" onClick={onClose} data-testid="button-cancel-faq">Cancelar</Button><SavingButton pending={pending}>{faq ? 'Guardar cambios' : 'Agregar pregunta'}</SavingButton></div></form></Modal>;
}

export default function Faqs() {
  const [serviceId, setServiceId] = useState(''); const [search, setSearch] = useState(''); const [editor, setEditor] = useState<Faq | 'new' | null>(null);
  const services = useListServices({ query: { queryKey: getListServicesQueryKey() } }); const params = serviceId ? { serviceId: Number(serviceId) } : undefined; const query = useListFaqs(params, { query: { queryKey: getListFaqsQueryKey(params) } }); const remove = useDeleteFaq(); const { toast } = useToast(); const client = useQueryClient();
  const list = useMemo(() => (query.data ?? []).filter((faq) => `${faq.question} ${faq.answer} ${faq.serviceName ?? ''}`.toLowerCase().includes(search.toLowerCase())), [query.data, search]);
  const removeFaq = (faq: Faq) => { if (!window.confirm('¿Eliminar esta pregunta del bot?')) return; remove.mutate({ id: faq.id }, { onSuccess: () => { void client.invalidateQueries({ queryKey: getListFaqsQueryKey() }); toast({ title: 'Pregunta eliminada' }); }, onError: () => toast({ title: 'No se pudo eliminar', variant: 'destructive' as const }) }); };
  return <AppShell><PageHeader eyebrow="Conversaciones que cuidan" title="Preguntas del bot" description="Dale al bot la información correcta para que recepción pueda enfocarse en lo importante." action={<Button onClick={() => setEditor('new')} data-testid="button-new-faq"><Plus size={16} />Nueva pregunta</Button>} />
    <div className="mb-5 grid gap-3 sm:grid-cols-[minmax(0,1fr)_220px]"><div className="relative"><Search size={16} className="absolute left-3 top-3 text-muted-foreground" /><input value={search} onChange={(e) => setSearch(e.target.value)} className={`${inputClass} pl-9`} placeholder="Buscar en preguntas y respuestas" data-testid="input-search-faqs" /></div><div className="relative"><select value={serviceId} onChange={(e) => setServiceId(e.target.value)} className={`${inputClass} appearance-none`} data-testid="select-filter-faqs"><option value="">Todos los tratamientos</option>{(services.data ?? []).map((service) => <option key={service.id} value={service.id}>{service.name}</option>)}</select><SelectChevron /></div></div>
    {query.isLoading ? <LoadingRows count={4} /> : query.isError ? <ErrorState onRetry={() => void query.refetch()} /> : list.length === 0 ? <EmptyState title={search || serviceId ? 'No hay coincidencias' : 'El bot aún no tiene respuestas'} description={search || serviceId ? 'Prueba otro término o cambia el filtro.' : 'Agrega preguntas frecuentes para que el bot pueda orientar con calidez.'} action={!search && !serviceId && <Button onClick={() => setEditor('new')} data-testid="button-empty-faq"><Plus size={15} />Agregar pregunta</Button>} /> :
      <div className="space-y-3">{list.map((faq) => <article key={faq.id} className="surface rounded-2xl p-5 transition-colors hover:border-primary/30" data-testid={`card-faq-${faq.id}`}><div className="flex items-start gap-4"><span className="hidden h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-secondary text-primary sm:flex"><CircleHelp size={17} /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="text-[10px] font-bold uppercase tracking-[.12em] text-primary">{faq.serviceName ?? 'General'}</span><StatusPill status={faq.active ? 'active' : 'inactive'} /></div><h2 className="mt-2 text-sm font-semibold">{faq.question}</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{faq.answer}</p></div><div className="flex shrink-0 gap-1"><Button variant="ghost" className="h-8 w-8 px-0" onClick={() => setEditor(faq)} aria-label="Editar pregunta" data-testid={`button-edit-faq-${faq.id}`}><Pencil size={14} /></Button><Button variant="ghost" className="h-8 w-8 px-0 text-destructive hover:bg-destructive/10" onClick={() => removeFaq(faq)} aria-label="Eliminar pregunta" data-testid={`button-delete-faq-${faq.id}`}><Trash2 size={14} /></Button></div></div><div className="mt-4 flex items-center justify-between border-t border-border/60 pt-3 text-[11px] text-muted-foreground"><span>Prioridad {faq.priority}</span><span className="flex items-center gap-1 font-semibold text-primary">Respuesta entrenada <ArrowUpRight size={13} /></span></div></article>)}</div>}
    {editor && <FaqEditor faq={editor === 'new' ? undefined : editor} services={services.data ?? []} onClose={() => setEditor(null)} />}
  </AppShell>;
}