import { Pencil, Plus, Power, Search, Scissors, Trash2 } from 'lucide-react';
import { useMemo, useState } from 'react';
import { getListServicesQueryKey, useCreateService, useDeleteService, useListServices, useUpdateService, type Service } from '@workspace/api-client-react';
import { useQueryClient } from '@tanstack/react-query';
import { AppShell } from '@/components/shell';
import { Button, EmptyState, ErrorState, Field, LoadingRows, Modal, PageHeader, SavingButton, SelectChevron, StatusPill, inputClass, textareaClass } from '@/components/common';
import { useToast } from '@/hooks/use-toast';

type ServiceForm = { name: string; slug: string; description: string; price: string; durationMinutes: string; category: string; active: boolean };
const blank: ServiceForm = { name: '', slug: '', description: '', price: '', durationMinutes: '60', category: '', active: true };

function ServiceEditor({ service, onClose }: { service?: Service; onClose: () => void }) {
  const [form, setForm] = useState<ServiceForm>(service ? { name: service.name, slug: service.slug, description: service.description, price: String(service.price), durationMinutes: String(service.durationMinutes), category: service.category, active: service.active } : blank);
  const create = useCreateService(); const update = useUpdateService(); const { toast } = useToast(); const queryClient = useQueryClient();
  const pending = create.isPending || update.isPending;
  const change = (key: keyof ServiceForm, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
  const submit = (event: React.FormEvent) => { event.preventDefault(); const data = { name: form.name.trim(), slug: form.slug.trim() || form.name.toLowerCase().trim().replaceAll(' ', '-'), description: form.description.trim(), price: Number(form.price), durationMinutes: Number(form.durationMinutes), category: form.category.trim(), active: form.active };
    const options = { onSuccess: () => { void queryClient.invalidateQueries({ queryKey: getListServicesQueryKey() }); toast({ title: service ? 'Tratamiento actualizado' : 'Tratamiento creado', description: 'El catálogo ya refleja tus cambios.' }); onClose(); }, onError: () => toast({ title: 'No se pudo guardar', description: 'Revisa los datos e intenta de nuevo.', variant: 'destructive' as const }) };
    if (service) update.mutate({ id: service.id, data }, options); else create.mutate({ data }, options);
  };
  return <Modal title={service ? 'Editar tratamiento' : 'Nuevo tratamiento'} description="Información que verá tu equipo al agendar una cita." onClose={onClose} wide><form onSubmit={submit} className="space-y-5">
    <div className="grid gap-4 sm:grid-cols-2"><Field label="Nombre"><input required value={form.name} onChange={(e) => change('name', e.target.value)} className={inputClass} placeholder="Ej. Limpieza facial" data-testid="input-service-name" /></Field><Field label="Categoría"><div className="relative"><input required value={form.category} onChange={(e) => change('category', e.target.value)} className={inputClass} placeholder="Facial, cuerpo..." data-testid="input-service-category" /><SelectChevron /></div></Field></div>
    <Field label="Descripción"><textarea required value={form.description} onChange={(e) => change('description', e.target.value)} className={textareaClass} placeholder="Una descripción breve y cálida del tratamiento." data-testid="input-service-description" /></Field>
    <div className="grid gap-4 sm:grid-cols-3"><Field label="Precio (MXN)"><input required min="0" type="number" value={form.price} onChange={(e) => change('price', e.target.value)} className={inputClass} placeholder="850" data-testid="input-service-price" /></Field><Field label="Duración (min)"><input required min="1" type="number" value={form.durationMinutes} onChange={(e) => change('durationMinutes', e.target.value)} className={inputClass} data-testid="input-service-duration" /></Field><Field label="Slug"><input required value={form.slug} onChange={(e) => change('slug', e.target.value)} className={inputClass} placeholder="limpieza-facial" data-testid="input-service-slug" /></Field></div>
    <label className="flex items-center gap-3 rounded-xl bg-muted/60 p-3 text-sm"><input type="checkbox" checked={form.active} onChange={(e) => change('active', e.target.checked)} className="h-4 w-4 accent-primary" data-testid="input-service-active" /><span><span className="block font-semibold">Disponible para agendar</span><span className="block text-xs text-muted-foreground">El bot podrá ofrecer este tratamiento.</span></span></label>
    <div className="flex justify-end gap-2 pt-2"><Button type="button" variant="ghost" onClick={onClose} data-testid="button-cancel-service">Cancelar</Button><SavingButton pending={pending}>{service ? 'Guardar cambios' : 'Agregar tratamiento'}</SavingButton></div>
  </form></Modal>;
}

export default function Services() {
  const query = useListServices({ query: { queryKey: getListServicesQueryKey() } });
  const [search, setSearch] = useState(''); const [editor, setEditor] = useState<Service | 'new' | null>(null);
  const remove = useDeleteService(); const { toast } = useToast(); const client = useQueryClient();
  const services = useMemo(() => (query.data ?? []).filter((item) => `${item.name} ${item.category}`.toLowerCase().includes(search.toLowerCase())), [query.data, search]);
  const deactivate = (service: Service) => { if (!window.confirm(`¿Desactivar ${service.name}?`)) return; remove.mutate({ id: service.id }, { onSuccess: () => { void client.invalidateQueries({ queryKey: getListServicesQueryKey() }); toast({ title: 'Tratamiento desactivado', description: `${service.name} ya no aparecerá para nuevas citas.` }); }, onError: () => toast({ title: 'No se pudo desactivar', variant: 'destructive' as const }) }); };
  return <AppShell><PageHeader eyebrow="Catálogo de cuidado" title="Tratamientos" description="Precios claros y servicios listos para que el bot los ofrezca con confianza." action={<Button onClick={() => setEditor('new')} data-testid="button-new-service"><Plus size={16} />Nuevo tratamiento</Button>} />
    <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="relative max-w-sm flex-1"><Search size={16} className="absolute left-3 top-3 text-muted-foreground" /><input value={search} onChange={(e) => setSearch(e.target.value)} className={`${inputClass} pl-9`} placeholder="Buscar tratamiento o categoría" data-testid="input-search-services" /></div><span className="text-xs text-muted-foreground">{services.length} tratamiento{services.length !== 1 ? 's' : ''}</span></div>
    {query.isLoading ? <LoadingRows count={5} /> : query.isError ? <ErrorState onRetry={() => void query.refetch()} /> : services.length === 0 ? <EmptyState title={search ? 'No encontramos ese tratamiento' : 'Tu catálogo comienza aquí'} description={search ? 'Prueba con otro nombre o categoría.' : 'Agrega el primer servicio para que recepción y WhatsApp hablen el mismo idioma.'} action={!search && <Button onClick={() => setEditor('new')} data-testid="button-empty-service"><Plus size={15} />Agregar tratamiento</Button>} /> :
      <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{services.map((service) => <article key={service.id} className="surface group rounded-2xl p-5 transition-transform hover:-translate-y-0.5" data-testid={`card-service-${service.id}`}><div className="flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-secondary text-primary"><Scissors size={18} /></span><StatusPill status={service.active ? 'active' : 'inactive'} /></div><div className="mt-5"><div className="flex items-start justify-between gap-3"><h2 className="text-[15px] font-semibold">{service.name}</h2><span className="whitespace-nowrap text-sm font-bold text-primary">${service.price.toLocaleString('es-MX')} <small className="text-[10px] font-medium text-muted-foreground">MXN</small></span></div><p className="mt-2 min-h-[40px] text-xs leading-relaxed text-muted-foreground">{service.description}</p><div className="mt-4 flex items-center gap-3 text-[11px] font-semibold text-muted-foreground"><span>{service.category}</span><span className="h-1 w-1 rounded-full bg-border" /><span>{service.durationMinutes} min</span></div></div><div className="mt-5 flex gap-2 border-t border-border/70 pt-4"><Button variant="ghost" className="h-8 flex-1 px-2 text-xs" onClick={() => setEditor(service)} data-testid={`button-edit-service-${service.id}`}><Pencil size={13} />Editar</Button><Button variant="ghost" className="h-8 px-2 text-xs" onClick={() => deactivate(service)} disabled={remove.isPending} aria-label={`Desactivar ${service.name}`} data-testid={`button-delete-service-${service.id}`}><Trash2 size={14} /></Button><Button variant="ghost" className="h-8 px-2 text-xs" onClick={() => setEditor({ ...service, active: !service.active })} aria-label="Cambiar disponibilidad" data-testid={`button-toggle-service-${service.id}`}><Power size={14} /></Button></div></article>)}</div>}
    {editor && <ServiceEditor service={editor === 'new' ? undefined : editor} onClose={() => setEditor(null)} />}
  </AppShell>;
}